# Generated by Django 5.2.7 on 2025-11-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
    ]
